In [94]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [119]:
df=pd.read_csv("Imdb_movies.csv")
df.head(5)

Unnamed: 0                                       Title  Release_year  \
0           0                                      Avatar          2009   
1           1                           Avengers: Endgame          2019   
2           2                    Avatar: The Way of Water          2022   
3           3                                     Titanic          1997   
4           4  Star Wars: Episode VII - The Force Awakens          2015   

  Certificate  Rating Runtime(min)   Genre  Metascore         Director  \
0          UA     7.9      162 min  Action       83.0    James Cameron   
1          UA     8.4      181 min  Action       78.0  Anthony Russo,    
2          UA     7.6      192 min  Action       67.0    James Cameron   
3          UA     7.9      194 min   Drama       75.0    James Cameron   
4           U     7.8      138 min  Action       80.0      J.J. Abrams   

                 Stars      Votes        Gross($)  
0    Sam Worthington,   13,58,528  2,92,37,06,026  
1  Robert Downey Jr.,   12,08,382  2,79,94,39,100  
2    Sam Worthington,    4,52,123  2,32,02,50,281  
3  Leonardo DiCaprio,   12,43,407  2,26,47,43,305  
4       Daisy Ridley,    9,54,781  2,07,13,10,218

In [120]:
df.drop(["Unnamed: 0"],axis=1,inplace=True)

In [121]:
df.head(5)

Title  Release_year Certificate  \
0                                      Avatar          2009          UA   
1                           Avengers: Endgame          2019          UA   
2                    Avatar: The Way of Water          2022          UA   
3                                     Titanic          1997          UA   
4  Star Wars: Episode VII - The Force Awakens          2015           U   

   Rating Runtime(min)   Genre  Metascore         Director  \
0     7.9      162 min  Action       83.0    James Cameron   
1     8.4      181 min  Action       78.0  Anthony Russo,    
2     7.6      192 min  Action       67.0    James Cameron   
3     7.9      194 min   Drama       75.0    James Cameron   
4     7.8      138 min  Action       80.0      J.J. Abrams   

                 Stars      Votes        Gross($)  
0    Sam Worthington,   13,58,528  2,92,37,06,026  
1  Robert Downey Jr.,   12,08,382  2,79,94,39,100  
2    Sam Worthington,    4,52,123  2,32,02,50,281  
3  Leonardo DiCaprio,   12,43,407  2,26,47,43,305  
4       Daisy Ridley,    9,54,781  2,07,13,10,218

In [122]:
df.isnull().sum()

Title            0
Release_year     0
Certificate     50
Rating           0
Runtime(min)     0
Genre            0
Metascore       38
Director         0
Stars            0
Votes            0
Gross($)         0
dtype: int64

In [123]:
df.dropna(how="any",axis=0,inplace=True)

In [124]:
df.head(2)

Title  Release_year Certificate  Rating Runtime(min)   Genre  \
0             Avatar          2009          UA     7.9      162 min  Action   
1  Avengers: Endgame          2019          UA     8.4      181 min  Action   

   Metascore         Director                Stars      Votes        Gross($)  
0       83.0    James Cameron    Sam Worthington,   13,58,528  2,92,37,06,026  
1       78.0  Anthony Russo,   Robert Downey Jr.,   12,08,382  2,79,94,39,100

In [125]:
df.isnull().sum()

Title           0
Release_year    0
Certificate     0
Rating          0
Runtime(min)    0
Genre           0
Metascore       0
Director        0
Stars           0
Votes           0
Gross($)        0
dtype: int64

In [126]:
df.dtypes

Title            object
Release_year      int64
Certificate      object
Rating          float64
Runtime(min)     object
Genre            object
Metascore       float64
Director         object
Stars            object
Votes            object
Gross($)         object
dtype: object

In [127]:
# Convert Votes and Gross into integers

In [128]:
df.Votes

0      13,58,528
1      12,08,382
2       4,52,123
3      12,43,407
4       9,54,781
         ...    
994     1,29,090
995     2,25,522
997     1,79,069
998     1,92,304
999     1,41,094
Name: Votes, Length: 943, dtype: object

In [129]:
No_Votes=[]
for i in df.Votes:
    a=i.replace(",","")
    No_Votes.append(int(a))

In [130]:
len(No_Votes)

943

In [131]:
Gross=[]
for i in df["Gross($)"]:
    a=i.replace(",","")
    Gross.append(int(a))

In [132]:
len(Gross)

943

In [133]:
df["No_Votes"]=No_Votes
df["Gross"]=Gross

In [134]:
df.drop(["Votes","Gross($)"],axis=1,inplace=True)

In [135]:
# Change the Gross column name into Gross($)
df.rename(columns={"Gross":"Gross($)"},inplace=True)

In [136]:
df.head(3)

Title  Release_year Certificate  Rating Runtime(min)  \
0                    Avatar          2009          UA     7.9      162 min   
1         Avengers: Endgame          2019          UA     8.4      181 min   
2  Avatar: The Way of Water          2022          UA     7.6      192 min   

    Genre  Metascore         Director                Stars  No_Votes  \
0  Action       83.0    James Cameron    Sam Worthington,    1358528   
1  Action       78.0  Anthony Russo,   Robert Downey Jr.,    1208382   
2  Action       67.0    James Cameron    Sam Worthington,     452123   

     Gross($)  
0  2923706026  
1  2799439100  
2  2320250281

In [139]:
# Convert Runtime type into int
Run_time=[]
for i in df["Runtime(min)"]:
    a=i.replace("min","")
    Run_time.append(int(a))
   

In [143]:
df["Run_Time(min)"]=Run_time

In [145]:
df.drop(["Runtime(min)"],axis=1,inplace=True)

In [146]:
df.head(2)

Title  Release_year Certificate  Rating   Genre  Metascore  \
0             Avatar          2009          UA     7.9  Action       83.0   
1  Avengers: Endgame          2019          UA     8.4  Action       78.0   

          Director                Stars  No_Votes    Gross($)  Run_Time(min)  
0    James Cameron    Sam Worthington,    1358528  2923706026            162  
1  Anthony Russo,   Robert Downey Jr.,    1208382  2799439100            181

In [147]:
df.dtypes

Title             object
Release_year       int64
Certificate       object
Rating           float64
Genre             object
Metascore        float64
Director          object
Stars             object
No_Votes           int64
Gross($)           int64
Run_Time(min)      int64
dtype: object

In [149]:
# find duplicate values if exist.
df.loc[df.duplicated(keep="first"),:] #There is no duplicated values. 

Empty DataFrame
Columns: [Title, Release_year, Certificate, Rating, Genre, Metascore, Director, Stars, No_Votes, Gross($), Run_Time(min)]
Index: []

In [152]:
df.Release_year.unique()

array([2009, 2019, 2022, 1997, 2015, 2018, 2021, 2012, 2011, 2023, 2017,
       2013, 2016, 2003, 1993, 2014, 2010, 2006, 1999, 2001, 2008, 1994,
       2007, 2002, 2004, 2005, 1996, 1982, 1977, 1998, 2000, 1980, 1991,
       1990, 1992, 1975, 1983, 1989, 2020, 1973, 1939, 1978, 1995, 1981,
       1985, 1986, 1988, 1984, 1987, 1942, 1972, 1961, 1979, 1967, 1937],
      dtype=int64)

In [153]:
df.Certificate.unique()

array(['UA', 'U', 'A', '12+', 'U/A', 'R', '(Banned)', '16', '15+', '7',
       'PG', '18', '13', 'PG-13', 'UA 16+', 'G', 'Not Rated'],
      dtype=object)

In [154]:
df.Rating.unique()

array([7.9, 8.4, 7.6, 7.8, 8.2, 6.9, 6.8, 8. , 7.1, 8.3, 7.3, 8.1, 6.1,
       7.4, 6.6, 6.4, 9. , 6.2, 5.6, 6.5, 7.7, 8.5, 8.8, 7.5, 6.3, 6.7,
       5.5, 5.9, 7. , 7.2, 5.8, 8.6, 8.7, 5.2, 4.9, 4.8, 5.1, 4.2, 5.4,
       4.5, 5.7, 6. , 5.3, 4.6, 4.3, 5. , 4. , 9.2, 3.8, 3.4, 8.9])

In [155]:
df.Genre.unique()

array(['Action', 'Drama', 'Animation', 'Adventure', 'Crime', 'Biography',
       'Mystery', 'Horror', 'Comedy', 'Documentary', 'Fantasy'],
      dtype=object)

In [156]:
df.Metascore.unique()

array([ 83.,  78.,  67.,  75.,  80.,  68.,  71.,  59.,  55.,  69.,  64.,
        66.,  88.,  85.,  46.,  84.,  51.,  65.,  56.,  62.,  94.,  81.,
        42.,  32.,  53.,  92.,  45.,  49.,  77.,  58.,  38.,  50.,  60.,
        87.,  90.,  63.,  61.,  73.,  44.,  74.,  76.,  35.,  52.,  82.,
        39.,  86.,  72.,  57.,  96.,  40.,  70.,  79.,  54.,  47.,  27.,
        48.,  30.,  41.,  95.,  43.,  31.,  91.,  34.,  97.,  33.,  24.,
        26.,  20.,  28.,  37.,  89., 100.,  19.,  36.,  23.,  21.,  12.,
        25.])

In [157]:
df.Director.unique()

array(['James Cameron', 'Anthony Russo, ', 'J.J. Abrams', 'Jon Watts',
       'Colin Trevorrow', 'Jon Favreau', 'Joss Whedon', 'James Wan',
       'Joseph Kosinski', 'Chris Buck, ', 'Ryan Coogler', 'David Yates',
       'Aaron Horvath, ', 'Rian Johnson', 'J.A. Bayona', 'Bill Condon',
       'Brad Bird', 'F. Gary Gray', 'Shane Black', 'Kyle Balda, ',
       'Peter Jackson', 'Sam Mendes', 'Anna Boden, ', 'Michael Bay',
       'Steven Spielberg', 'Christopher Nolan', 'Todd Phillips',
       'Josh Cooley', 'Lee Unkrich', 'Gore Verbinski', 'Gareth Edwards',
       'Guy Ritchie', 'Rob Marshall', 'Andrew Stanton, ', 'George Lucas',
       'Byron Howard, ', 'Tim Burton', 'Chris Columbus', 'Jake Kasdan',
       'Pierre Coffin, ', 'Roger Allers, ', 'Sam Raimi',
       'Andrew Adamson, ', 'Bryan Singer', 'Mike Newell', 'Chris Renaud',
       'Carlos Saldanha, ', 'Steve Martino, ', 'Zack Snyder',
       'Francis Lawrence', 'James Gunn', 'Pete Docter, ',
       'Ruben Fleischer', 'Taika Waititi', '

In [158]:
df.Stars.unique()

array(['Sam Worthington, ', 'Robert Downey Jr., ', 'Leonardo DiCaprio, ',
       'Daisy Ridley, ', 'Tom Holland, ', 'Chris Pratt, ',
       'Donald Glover, ', 'Vin Diesel, ', 'Tom Cruise, ',
       'Kristen Bell, ', 'Chadwick Boseman, ', 'Daniel Radcliffe, ',
       'Emma Watson, ', 'Craig T. Nelson, ', 'Sandra Bullock, ',
       'Chris Evans, ', 'Jason Momoa, ', 'Elijah Wood, ',
       'Daniel Craig, ', 'Brie Larson, ', 'Shia LaBeouf, ', 'Sam Neill, ',
       'Mark Wahlberg, ', 'Christian Bale, ', 'Joaquin Phoenix, ',
       'Tom Hanks, ', 'Johnny Depp, ', 'Felicity Jones, ', 'Will Smith, ',
       'Steve Carell, ', 'Ellen DeGeneres, ', 'Ewan McGregor, ',
       'Ginnifer Goodwin, ', 'Mia Wasikowska, ', 'Martin Freeman, ',
       'Dwayne Johnson, ', 'Matthew Broderick, ', 'Neel Sethi, ',
       'Ian McKellen, ', 'Benedict Cumberbatch, ', 'Albert Brooks, ',
       'Mike Myers, ', 'Rami Malek, ', 'Tobey Maguire, ', 'Louis C.K., ',
       'Ray Romano, ', 'Ben Affleck, ', 'Hayden Christen

In [160]:
df["Run_Time(min)"].unique()

array([162, 181, 192, 194, 138, 149, 148, 124, 118, 143, 137, 130, 103,
       141, 134,  92, 152, 128, 102, 129, 136,  91, 147, 201, 123, 154,
       127, 165, 164, 122, 100, 151, 133,  89,  97, 108, 169, 119, 146,
        98,  88, 106, 144, 161, 126, 179,  87, 153,  93, 178, 157, 139,
        94, 140,  95, 112, 115, 150, 121, 145, 105, 132, 142, 158, 163,
       176, 104,  96, 117, 135, 131, 107,  90, 120, 111, 116, 101, 125,
       187,  86, 156, 113,  85, 155, 114, 110, 183, 109,  84, 180, 238,
        81,  82,  83, 166, 195,  99, 159, 189,  69, 175,  79, 170,  78,
        80, 167,  72], dtype=int64)

In [161]:
df

Title  Release_year Certificate  \
0                                        Avatar          2009          UA   
1                             Avengers: Endgame          2019          UA   
2                      Avatar: The Way of Water          2022          UA   
3                                       Titanic          1997          UA   
4    Star Wars: Episode VII - The Force Awakens          2015           U   
..                                          ...           ...         ...   
994                                   Allegiant          2016          13   
995                                   Daredevil          2003          UA   
997                 He's Just Not That Into You          2009          13   
998                                   Eagle Eye          2008           A   
999                            Along Came Polly          2004          UA   

     Rating   Genre  Metascore             Director                Stars  \
0       7.9  Action       83.0        James Cameron    Sam Worthington,    
1       8.4  Action       78.0      Anthony Russo,   Robert Downey Jr.,    
2       7.6  Action       67.0        James Cameron    Sam Worthington,    
3       7.9   Drama       75.0        James Cameron  Leonardo DiCaprio,    
4       7.8  Action       80.0          J.J. Abrams       Daisy Ridley,    
..      ...     ...        ...                  ...                  ...   
994     5.7  Action       33.0     Robert Schwentke   Shailene Woodley,    
995     5.3  Action       42.0  Mark Steven Johnson        Ben Affleck,    
997     6.4  Comedy       47.0           Ken Kwapis   Ginnifer Goodwin,    
998     6.6  Action       43.0          D.J. Caruso       Shia LaBeouf,    
999     6.0  Comedy       44.0         John Hamburg        Ben Stiller,    

     No_Votes    Gross($)  Run_Time(min)  
0     1358528  2923706026            162  
1     1208382  2799439100            181  
2      452123  2320250281            192  
3     1243407  2264743305            194  
4      954781  2071310218            138  
..        ...         ...            ...  
994    129090   179246868            120  
995    225522   179179718            103  
997    179069   178866158            129  
998    192304   178767383            118  
999    141094   178311729             90  

[943 rows x 11 columns]